apiVersion: v1
kind: ConfigMap
metadata:
  name: edtech-config
  namespace: default
data:
  NODE_ENV: "production"
  # URL interna para que el frontend hable con el catálogo
  CATALOG_API_URL: "http://ms-catalog-service.default.svc.cluster.local" 
---
apiVersion: v1
kind: Secret
metadata:
  name: edtech-secrets
  namespace: default
type: Opaque
stringData:
  # Kubernetes lo encriptará automáticamente en Base64 por debajo
  jwt-secret: "ClaveUltraSecretaParaTokensJWT2026"
  db-password: "PasswordSeguro123"