apiVersion: v1
kind: ConfigMap
metadata:
  name: edtech-config
  namespace: default
data:
  NODE_ENV: "production"
  # URL interna para que el frontend hable con el catálogo
  CATALOG_API_URL: "http://ms-catalog-service.default.svc.cluster.local" 

  VIDEO_CDN_URL: "https://d2b80shv6gf6on.cloudfront.net"

  DATABASE_URL: "pi-database.c1gg6qawugpv.sa-east-1.rds.amazonaws.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: edtech-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "ClaveUltraSecretaParaTokensJWT2026"
  db-password: "PasswordSeguro123"